
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package dao;

import entities.Utilisateur;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collection;

/**
 *
 * @author Caroline Bergé
 */
public class UtilisateurDAO extends DAO<Utilisateur> {

    public UtilisateurDAO() {
        super("Utilisateur");
    }

    @Override
    public Utilisateur read(Integer id) {
        Utilisateur obj = null;
        String sql = "SELECT * FROM Utilisateur WHERE id_Utilisateur=?";
        PreparedStatement pstmt;
        try {
            pstmt = connexion.prepareStatement(sql);
            pstmt.setInt(1, id);
            ResultSet rs = pstmt.executeQuery();
            if (rs.first()) {
                obj = new Utilisateur();
                obj.setId(rs.getInt("id_Utilisateur"));
                obj.setPseudo(rs.getString("pseudo"));
                obj.setMot_de_passe(rs.getString("mot_de_passe"));
                obj.setEstActif(rs.getBoolean("estActif"));
            }
        } catch (SQLException ex) {
            System.err.println("Erreur lors de la lecture : " + ex.getMessage());
        }
        return obj;
    }

    public Utilisateur read(String login) {
        Utilisateur obj = null;
        String sql = "SELECT * FROM Utilisateur WHERE pseudo=?";
        PreparedStatement pstmt;
        try {
            pstmt = connexion.prepareStatement(sql);
            pstmt.setString(1, login);
            ResultSet rs = pstmt.executeQuery();
            if (rs.first()) {
                obj = new Utilisateur();
                obj.setId(rs.getInt("id_Utilisateur"));
                obj.setPseudo(rs.getString("pseudo"));
                obj.setMot_de_passe(rs.getString("mot_de_passe"));
                obj.setEstActif(rs.getBoolean("estActif"));

            }
        } catch (SQLException ex) {
            System.err.println("Erreur lors de la lecture : " + ex.getMessage());
        }
        return obj;
    }

    @Override
    public void create(Utilisateur obj) {
        String sql = "INSERT INTO Utilisateur (pseudo, mot_de_passe, estActif) "
                + "VALUES (?, ?, ?)";
        try {
            PreparedStatement pstmt = connexion
                    .prepareStatement(
                            sql,
                            PreparedStatement.RETURN_GENERATED_KEYS
                    );
            pstmt.setString(1, obj.getPseudo());
            pstmt.setString(2, obj.getMot_de_passe());
            pstmt.setBoolean(3, obj.getEstActif());
            int nbLines = pstmt.executeUpdate();
            if (nbLines == 1) {
                ResultSet autoGeneratedKeys = pstmt.getGeneratedKeys();
                autoGeneratedKeys.first();
                int id = autoGeneratedKeys.getInt(1);
                obj.setId(id);
            }
        } catch (SQLException ex) {
            System.err.println("Erreur lors de l'insertion : " + ex.getMessage());
        }
    }

    @Override
    public void update(Utilisateur obj) {
        String sql = "UPDATE Utilisateur SET pseudo=?, mot_de_passe=?, estActif=? "
                + "WHERE id_Utilisateur=?";
        try {
            PreparedStatement pstmt = connexion.prepareStatement(sql);
            pstmt.setString(1, obj.getPseudo());
            pstmt.setString(2, obj.getMot_de_passe());

            pstmt.setBoolean(3, obj.getEstActif());
            pstmt.setInt(4, obj.getId());

            pstmt.executeUpdate();
        } catch (SQLException ex) {
            System.err.println("Erreur lors de l'update : " + ex.getMessage());
        }
    }

    @Override
    public void delete(Integer id) {
        String sql = "DELETE FROM Utilisateur WHERE id_Utilisateur=?";
        try {
            PreparedStatement pstmt = connexion.prepareStatement(sql);
            pstmt.setInt(1, id);
            pstmt.executeUpdate();
        } catch (SQLException ex) {
            System.err.println("Erreur lors du delete : " + ex.getMessage());
        }
    }

    @Override
    public int count() {
        int count = 0;
        String sql = "SELECT FROM AS c FROM Utilisateur";
        try {
            PreparedStatement pstmt = connexion.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            if (rs.first()) {
                count = rs.getInt("c");
            }
        } catch (SQLException ex) {
            System.err.println("Erreur lors du comptage : " + ex.getMessage());
        }
        return count;
    }

    @Override
    public Collection<Utilisateur> list() {
        ArrayList<Utilisateur> list = new ArrayList<>();
        String sql = "SELECT * FROM Utilisateur";
        try {
            PreparedStatement pstmt = connexion.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            while (rs.next()) {
                Utilisateur p = new Utilisateur();
                p.setId(rs.getInt("id_Utilisateur"));
                p.setPseudo(rs.getString("pseudo"));
                p.setMot_de_passe(rs.getString("mot_de_passe"));
                p.setEstActif(rs.getBoolean("estActif"));

                list.add(p);
            }
        } catch (SQLException ex) {
            System.err.println("Erreur lors du listage : " + ex.getMessage());
        }
        return list;
    }

    @Override
    protected Utilisateur createObject(ResultSet rs) throws SQLException {
        Utilisateur obj = new Utilisateur();
        obj.setId(rs.getInt("id_" + table));
        obj.setPseudo(rs.getString("pseudo"));
        obj.setMot_de_passe(rs.getString("mot_de_passe"));
        obj.setEstActif(rs.getBoolean("estActif"));

        return obj;
    }

}
